const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const inmobiliarioSchema= new Schema({
    Latitud:String,
    Longitud:String,
    ID:String,
    Titulo:String,
    Anunciante:String,
    Descripcion:String,
    Reformado:String,
    Telefonos:String,
    Tipo:String,
    Precio:String,
    Precio_por_metro:String,
    Direccion:String,
    Provincia:String,
    Ciudad:String,
    Metroscuadrados:String,
    Habitaciones:String,
    Baños:String,
    Parking:String,
    Segunda_mano:String,
    Armariosempotrados:String,
    Construido_en:String,
    Amueblado:String,
    Calefaccionindividual:String,
    Certificacionenergetica:String,
    Planta:String,
    Exterior:String,
    Interior:String,
    Ascensor:String,
    Fecha:String,
    Calle:String,
    Barrio:String,
    Distrito:String,
    Terraza:String,
    Trastero:String,
    Cocina_equipada:String,
    Cocina_equipada:String,
    Aireacondicionado:String,
    Piscina:String,
    Jardín:String,
    Metroscuadradosutiles:String,
    Aptopersonamovilidadreducida:String,
    Plantas:String,
    Seadmitenmascotas:String,
    Balcón:String
})

module.exports=mongoose.model('inmobiliario',inmobiliarioSchema);